Repository marcpage/scheduling, pull requests merged in 2021-12, with the labels that each got.

#7 Now the admin can set a restaurant's gm
  src/scheduling.py
  src/ui/template/restaurant.html
Labels: enhancement

#8 add users to restaurant
  src/model.py
  src/scheduling.py
  src/ui/template/restaurant.html
  src/ui/template/welcome.html
Labels: enhancement

#9 Adding restaurant roles which link users to their restaurant
  pr_build.sh
  src/model.py
  src/scheduling.py
  src/ui/template/restaurant.html
  src/ui/template/welcome.html
Labels: enhancement

#10 Do more duplicate users and tests added
  .gitignore
  pr_build.sh
  src/model.py
  src/scheduling.py
  src/tests/__init__.py
  src/tests/test_model.py
  src/ui/template/restaurant.html
  src/ui/template/welcome.html
Labels: enhancement

#27 Now we are using restaurant instead of gm in a few fields
  src/model.py
  src/ui/template/restaurant.html
Labels: bug

#30 Now users can change their role priority
  src/scheduling.py
  src/ui/template/welcome.html
Labels: enhancement

#33 Adding ability for gm to set employee-role priorities
  src/model.py
  src/scheduling.py
  src/ui/template/restaurant.html
  src/ui/template/welcome.html
Labels: enhancement

#35 Updating the model documentation
  src/model.py
  src/tests/test_model.py
Labels: enhancement

#39 First attempt at fixing pr_build failing the build
  pr_build.sh
  src/model.py
Labels: bug

#43 Now the first login will create the admin account
  src/scheduling.py
Labels: enhancement

#44 More GitHub log formatting for build_pr.sh
  pr_build.sh
Labels: enhancement

#46 Minor bug fixes and pr_build local experience improvements
  pr_build.sh
  src/scheduling.py
  src/ui/template/restaurant.html
  src/ui/template/welcome.html
Labels: bug

#47 We now have the ui for employee availability
  pr_build.sh
  src/model.py
  src/scheduling.py
  src/ui/template/restaurant.html
Labels: bug, enhancement

#48 Docs
  .gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/scheduling.iml
  .idea/vcs.xml
  src/model.py
  src/scheduling.py
  src/tests/test_model.py
Labels: documentation

#54 Now employees can report their availability.
  src/model.py
  src/scheduling.py
  src/ui/template/restaurant.html
Labels: enhancement

#56 adding doc-strings to functions I added
  src/scheduling.py
Labels: documentation

#57 Typo Fix
  README.md
Labels: documentation
